### ISSUE TITLE
Process() not in scope issue

### ISSUE THREAD

**Issue by gkvappium** [QiuZhiFei/swift-commands#7]
Hi @QiuZhiFei , I was trying to use this package so that I can run some command line stuff via swift to capture logs from an iPhone. But seems like there is an issue wherein it cannot find Process() in scope

![image](https://user-images.githubusercontent.com/27851378/171850970-d51ff3a2-4f69-4bb6-8e97-406b6b5df373.png)

Note: Swift Language Version is set to 5 in Build settings.

Am I missing something here in terms of the usage? Any help would be appreciated. Thanks

**Comment by QiuZhiFei** [comment]
swift-commands does not support iOS. @gkvappium
