### ISSUE TITLE
How to install the packages in Swift UI App ?

### ISSUE THREAD

**Issue by khanakia** [QiuZhiFei/swift-commands#9]
I do not see the package as shown in screenshot ? So how do i install it on Swift project ?

<img width="1392" alt="Screenshot 2022-08-27 at 8 07 35 AM" src="https://user-images.githubusercontent.com/2174170/187011033-f8418304-c3b0-420e-a598-5553386a3787.png">

**Comment by QiuZhiFei** [comment]
![截屏2024-03-05 20 58 32](https://github.com/QiuZhiFei/swift-commands/assets/3402799/459c5616-48a9-422e-a4b6-ed1303cbbb71)
